[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@morpho-org/morpho-blue=lib/morpho-blue/",
    "forge-std/=lib/forge-std/src/",
]

optimizer = true
optimizer_runs = 200
viaIR = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
